name: Python application CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # or specify exact version like '3.10' 3.9.6
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # If you use pytest, you might add:
        # pip install pytest
        
    - name: Run tests
      run: |
        # Add your test command here, for example:
        # python -m pytest
        echo "Tests would run here"
        
    # Optional: Add a deployment step
    # - name: Deploy
    #   run: |
    #     echo "Deployment would happen here"
    #   if: github.ref == 'refs/heads/main'